//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.07 at 11:04:30 AM CST 
//


package com.revature.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="superpet" type="{http://www.example.org/superpet}superpet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "superpet"
})
@XmlRootElement(name = "getSuperPetResponse")
public class GetSuperPetResponse {

    @XmlElement(required = true)
    protected Superpet superpet;

    /**
     * Gets the value of the superpet property.
     * 
     * @return
     *     possible object is
     *     {@link Superpet }
     *     
     */
    public Superpet getSuperpet() {
        return superpet;
    }

    /**
     * Sets the value of the superpet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Superpet }
     *     
     */
    public void setSuperpet(Superpet value) {
        this.superpet = value;
    }

}
